### ISSUE TITLE
test_noproxy_star fails

### ISSUE THREAD

**Issue by felixonmars** [httplib2/httplib2#103]
test_noproxy_star fails on both Python 2.7 and 3.6 here:

```
=================================== FAILURES ===================================
______________________________ test_noproxy_star _______________________________
tests/test_proxy.py:76: in test_noproxy_star
    assert not pi.applies_to(host)
E   AssertionError: assert not True
E    +  where True = <bound method ProxyInfo.applies_to of <ProxyInfo type=3 host:port=myproxy.example.com:80 rdns=True user=None headers=None>>('169.254.38.192')
E    +    where <bound method ProxyInfo.applies_to of <ProxyInfo type=3 host:port=myproxy.example.com:80 rdns=True user=None headers=None>> = <ProxyInfo type=3 host:port=myproxy.example.com:80 rdns=True user=None headers=None>.applies_to
```

**Comment by temoto** [comment]
How did you run tests? Does it also fail with `--forked` ?

**Comment by temoto** [comment]
Is it possible you run tests against older httplib2 in system packages?

**Comment by felixonmars** [comment]
I don't have httplib2 in the test system. I ran the tests using `python setup.py pytest --addopts tests`.

**Comment by temoto** [comment]
Archlinux?

**Comment by felixonmars** [comment]
Yes, I am packaging httplib2 for Arch.

**Comment by temoto** [comment]
I did not test setup.py in any way except for `sdist`. Recommended way to run tests is: `script/test --forked` is it fine to include that command into pkgbuild or do you need `setup.py test` api?

**Comment by felixonmars** [comment]
I would like to avoid the use of pip and venv if possible. The `setup.py pytest` command comes from `pytest-runner` and is meant to be the same as running pytest (with better path handling). I have tried to apply `--forked` and it indeed makes a difference. The test suite runs successfully with `python setup.py pytest --addopts "tests --forked"`.

If `--forked` is considered mandatory, it may make sense to include it in setup.cfg?

**Comment by temoto** [comment]
@felixonmars please check if this version helps: 031136e71ccb083efdcea1d778fd0e10b27f7e0b

`setup.py test` executes pytest with our flags, no virtualenv, no pip, no pytest-runner, `setup(tests_require=read(requirements-test.txt))` seems to work for me.

**Comment by felixonmars** [comment]
Sorry for the delay. The updated version works fine here :)

**Comment by temoto** [comment]
@felixonmars merged in master, I hope it helps the great ArchLinux.
