### ISSUE TITLE
Is the timeout passed on to an underlying Python socket as is?

### ISSUE THREAD

**Issue by gauteh** [httplib2/httplib2#104]
Hi, it was a little unclear for me when reading [the docs](http://httplib2.readthedocs.io/en/latest/libhttplib2.html) how the `timeout` parameter is handled. Is it passed on to the [socket timeouts](https://docs.python.org/3/library/socket.html#notes-on-socket-timeouts) as is? In that case, does the special values `None` and `0` mean the same as for the `socket`?

Also, does it make sense to have non-blocking timeout (`0`)?

Somewhat related: #32

**Comment by temoto** [comment]
- `timeout` is passed to socket as is, all special values mean same as for socket
- simply put, if you're asking then non-blocking `timeout=0` is definitely **harmful**

**Comment by gauteh** [comment]
Thanks, that clarifies it for me. Closing.
