### ISSUE TITLE
Standard library

### ISSUE THREAD

**Issue by 1oglop1** [httplib2/httplib2#124]
I wonder how is this different against https://docs.python.org/3.7/library/http.client.html

and if there is any effort to prevent this: https://github.com/urllib3/urllib3/issues/1482 ?

**Comment by 1oglop1** [comment]
Not right now but I'm writing lambda functions and I needed to modify this https://github.com/1oglop1/aws-cloudformation-templates/blob/master/community/custom_resources/python_custom_resource_helper/crhelper.py

Which made me thinking what's the best portable solution, since `botocore.vendored.requests` are slowly being deprecated, but lambda `py3.7` has `urllib3` 

My PR probably won't get accepted if it won't support legacy python

**Comment by temoto** [comment]
httplib2 is a great option for that use case, it has (all?) relevant high level features and really low overhead.

I understand your irritation with library zoo. It could use some ecosystem management. I'm not familiar with people who would take this job.
