### ISSUE TITLE
Connecting to local server

### ISSUE THREAD

**Issue by hyejung-rachel** [httplib2/httplib2#134]
I have a local server 127.0.0.1 running at port   ##8082.
I tried the following:
`import httplib2
h = httplib2.Http
(resp_headers, content) = h.request("http://127.0.0.1:8082", "GET")`

But the RelativeURIError was raised. 
I tried googling but could not find a solution. Can anyone help?

**Comment by temoto** [comment]
Please show `curl -v http://...`

**Comment by temoto** [comment]
Feel free to reopen if this is still relevant.
