### ISSUE TITLE
CHANGELOG needs an update

### ISSUE THREAD

**Issue by cclauss** [httplib2/httplib2#137]
https://github.com/httplib2/httplib2/blob/master/CHANGELOG

**Comment by temoto** [comment]
Would you please expand, how specifically it needs to be updated?

**Comment by cclauss** [comment]
https://github.com/httplib2/httplib2/releases shows that there is an undocumented release.  Is there some text that describes why users should upgrade?

**Comment by temoto** [comment]
That *tag* together with accompanying changelog is in
https://github.com/httplib2/httplib2/pull/136

It wasn't published on PyPI. What you see is GitHub implicit release
because there is a tag. Wrongly (for us), because it's not on master branch.
