### ISSUE TITLE
ResourceWarning: unclosed socket.socket

### ISSUE THREAD

**Issue by busunkim96** [httplib2/httplib2#148]
Hello!

Is there any way to 'close' an `httplib2.Http` object after you are done using it? Making a request seems to leave a socket open.

```python
import httplib2

http = httplib2.Http()
http.request("http://example.com")
```

```
$ python3 -Wall make-creds.py 
make-creds.py:6: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('2620:15c:10f:202:e603:43de:a156:cc2', 51260, 0, 0), raddr=('2606:2800:220:1:248:1893:25c8:1946', 80, 0, 0)>
```

**Comment by temoto** [comment]
Hello.

- We don't have a 'close' API yet. I'll make it shortly.
- HTTP/1.1+ mandates persistent connections by default, so all HTTP libraries keep sockets open in case you will send another request to same server.

**Comment by temoto** [comment]
@busunkim96 please try this version.

`pip install https://github.com/httplib2/httplib2/archive/581aaf66d333e173ecfd995a78729aaeaccef504.zip`

**Comment by busunkim96** [comment]
@temoto Thank you for the quick response and the PR!

**Comment by temoto** [comment]
@busunkim96 does it fix the warning for you?

**Comment by busunkim96** [comment]
@temoto :+1:  Yes, I don't get the warning if I use `.close()`.

```python
import httplib2

http = httplib2.Http()
http.request("http://example.com")
http.close()
```
