### ISSUE TITLE
DeprecationWarning over invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [httplib2/httplib2#155]
This code probably seems to fall under Python 2 but I just thought of filing a report. Feel free to close this if it's irrelevant.

```
find httplib2 -iname '*.py'  | xargs -P 4 -I{} python -Wall -m py_compile {}
httplib2/python2/httplib2/__init__.py:1338: DeprecationWarning: invalid escape sequence \.
  host_re = host.replace(".", "\.").replace("*", "[^.]*")
```

**Comment by temoto** [comment]
Thanks.

Were you using Python3 to compile Python2 code? Please check `python -V` to confirm.

This works without warnings:

```shell
# in httplib2 dir
find python2 -name '*.py'  |xargs python2 -Wall -m py_compile
```

Please reopen if it's not py2/3 mismatch thing. I like clean `-Wall` too.

**Comment by tirkarthi** [comment]
Yeah, I was using Python 3. I noticed from the folder name python2 this might not be relevant and executed with Python 3 but thought to file anyway. Thanks for the clarification.
