### ISSUE TITLE
Bypass hosts not used on HTTPSConnectionWithTimeout

### ISSUE THREAD

**Issue by joaomsan** [httplib2/httplib2#160]
Hello,

I was investigating why a https request that i was doing was using proxy even though i added the host to bypass_hosts.

I found out the the method HTTPConnectionWithTimeout.connect does the following 

line 1155 ` if self.proxy_info and self.proxy_info.isgood() and self.proxy_info.applies_to(self.host):`

But the method HTTPSConnectionWithTimeout.connect does the following
line 1287 `  if self.proxy_info and self.proxy_info.isgood():`

I think that the https connections are missing the **.applies_to**

**Comment by temoto** [comment]
Thanks, working on it.

Irrelevant statistics question, do you use httplib2 with Python 3+?

**Comment by joaomsan** [comment]
Yes, Python 3.6

Thank you for your prompt reply.

**Comment by temoto** [comment]
Please, try this patch

`pip install https://github.com/httplib2/httplib2/archive/e9a98f93c9e29a886231cf02a10b4dafa6793ef2.zip`

**Comment by temoto** [comment]
You were right about the problem line, although it works properly in Python 2.

Thanks for bringing this up, I added tests covering full relevant code path.

Sorry for trouble.

**Comment by joaomsan** [comment]
With this patch its working as expected, the proxy is no longer used.

Thank you very much.

**Comment by temoto** [comment]
@joaomsan please also try `pip install httplib2==0.17.1`
