### ISSUE TITLE
Force to use headers

### ISSUE THREAD

**Issue by qo4on** [httplib2/httplib2#167]
How can I set exactly the headers from my list?
I set headers:
```
headers = OrderedDict([
	('key1', 'va1l'),
	('key2', 'val2')
	...
])
```
But I see an additional header along with my headers in the request which I didn't write:
`Transfer-Encoding: chunked`
Is it possible to remove all default headers or set exactly the list of headers I want?

Also when I use `('Connection', 'keep-alive')` I see lowercased header `connection: keep-alive`. How can I fix this?

**Comment by temoto** [comment]
Show how to reproduce the problem, starting with this

```
virtualenv venv
venv/bin/pip install httplib2
venv/bin/python
>>> import httplib2
...
```

**Comment by qo4on** [comment]
Do this:
```
import httplib2, socks, json
from collections import OrderedDict
from urllib.parse import urlencode
h = httplib2.Http(proxy_info = httplib2.ProxyInfo(socks.PROXY_TYPE_HTTP, '127.0.0.1', 8888))
headers = OrderedDict([
	('User-Agent', ': Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36'),
	('Connection', 'keep-alive')
])

data = {"name": "Joe", "comment": "A test comment"}
resp, content = h.request("http://bitworking.org/news/223/Meet-Ares", "POST", urlencode(data), headers)
print(resp, content)
{'server': 'Varnish', 'retry-after': '0', 'location': 'https://bitworking.org/news/223/Meet-Ares', 'content-length': '0', 'accept-ranges': 'bytes', 'date': 'Thu, 21 May 2020 12:09:07 GMT', 'connection': 'close', 'x-served-by': 'cache-hhn4032-HHN', 'x-cache': 'HIT', 'x-cache-hits': '0', 'x-timer': 'S1590062948.570107,VS0,VE0', 'status': '301'} b''
```
And see the result in Fiddler's raw tab:
```
POST http://bitworking.org/news/223/Meet-Ares HTTP/1.1
Host: bitworking.org
Content-Length: 31
user-agent: : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
connection: keep-alive
accept-encoding: gzip, deflate

name=Joe&comment=A+test+comment
```

**Comment by temoto** [comment]
There is no transfer-encoding but without `Content-Length` or chunked transfer encoding, server doesn't know where your request body ends.

You can change `accept-encoding: gzip, deflate` to just `accept-encoding: ` with `headers={'accept-encoding': ''}` maybe we could accept None to omit sending a header. Patches are welcome. Compatibility with wider ecosystem is important too.

- `Host` is required for HTTP/1.1
- Header field name is case-insensitive per [RFC2616](https://tools.ietf.org/html/rfc2616#section-4.2) all following are equivalent:
  - `connection: keep-alive`
  - `Connection: keep-alive`
  - `cONNEctIOn: keep-alive`

**Comment by qo4on** [comment]
I understand that.
So, it is impossible to set the headers exactly using httplib2, right?

**Comment by temoto** [comment]
Correct. If you want to set headers with violation of HTTP protocol (case sensitive, remove `host` or request length) then your best option is to just open socket and write bytes.
