### ISSUE TITLE
HTTP pipelining

### ISSUE THREAD

**Issue by qo4on** [httplib2/httplib2#174]
How to send [multiple requests](https://brianbondy.com/static/img/blogpost_119/pipelining6requests.png) on the same socket without waiting for each response? is it possible for `httplib2`?

**Comment by temoto** [comment]
Sorry, no pipelining support yet. Unless someone puts a lot of work into it, also not going to happen soon.

**Comment by qo4on** [comment]
Thanks. [This article](https://brianbondy.com/blog/119/what-you-should-know-about-http-pipelining) says you do support.
