### ISSUE TITLE
When using http.close()?

### ISSUE THREAD

**Issue by yohplala** [httplib2/httplib2#178]
Hi,

I am using httplib2 in python function through Google API python client.
Recently was added to Google API python client [a `close()`method](https://github.com/googleapis/google-api-python-client/pull/1038) relying on [`http.close()`](https://github.com/httplib2/httplib2/blob/9bf300cdc372938f4237150d5b9b615879eb51a1/python3/httplib2/__init__.py#L1498-L1506).

My google Drive connector is a class:
- Google Drive service is created in `init` and becomes a property of my Google drive object. So I will certainly not use the `close()`method that was implemented in this lib as I need to re-use this `service`property afterwards.
- to manage 'thread-safety', I create an http object for each connection in a dedicated function (as recommended in [Google Drive documentation](https://github.com/googleapis/google-api-python-client/blob/master/docs/thread_safety.md#thread-safety)).

For instance to upload a file:
```python
import httplib2

def write(self, folder_id: str, file_name: str, **kwargs):
    # Upload (caching the authorized `http` object used to run `next_chunk()`)
    media = googleapiclient.http.MediaFileUpload(file_name, resumable=True)
    file_metadata = {'name': file_name, 'parents': [folder_id]}
    request = self.drive.files().create(body=file_metadata, media_body=media, fields='id')
    # Set timeout to 10 minutes for upload of big chunks (is used when creating the `http` object)
    socket.setdefaulttimeout(600)
    auth_http = googleapiclient._auth.authorized_http(self.creds)        # here, creation of my local http object
    auth_http.cache = httplib2.FileCache(self.cache_path)
    response = None
    while response is None:
        status, response = request.next_chunk(num_retries=4, http=auth_http)
                                                                         # shoud I add here a call to close this http object?
```

Ok, this all seems very Google API python client related, sorry for the long introduction. :)

Now the `httplib2` related question.
After the 10mn timeout I have setup in this `write()`function, will the `http`object naturally close, or do I have to call the `http.close()`method to ensure it is closed?

I thank you for your guidance.
Have a good day,
Bests,

**Comment by temoto** [comment]
In general you can call `Http.close()` when you know you will not be doing more requests to same hosts for a while. It only applies to long lived `Http` objects. If your `auth_http` goes out of scope and deleted by reference counter, it should close all connections without explicit `.close()` call.

Please open separate bug report if you observe background connections not closed after destructing `Http` object. That would be a bug.

**Comment by yohplala** [comment]
Thanks @temoto , crystal clear!
