### ISSUE TITLE
Timeout makes the next request to the same domain fail

### ISSUE THREAD

**Issue by honux** [httplib2/httplib2#18]
Heya.

Whenever a request fail with a socket.timeout, the following request to the same domain fails. Example:

``` python3
import httplib2
h = httplib2.Http(timeout=3)
h.force_exception_to_status_code = True

head_1, cont_1 = h.request('https://httpbin.org/delay/60', headers={'cache-control':'no-cache'})
# head_1: {'status': '408', 'content-type': 'text/plain', 'content-length': 15}
# cont_1: b'Request Timeout'

# right after the timeout, request anything to the same domain
head_2, cont_2 = h.request('https://httpbin.org/delay/2', headers={'cache-control':'no-cache'})
# Instead of a 2 second delay, it will reuse the connection made on the previous request, making the response timeout / have the response of the previous request.

```

I'm using the latest httplib2 and python3

---

If this is expected, is there any way to really 'drop' the connection? Forcing a new connection instead.

**Comment by justinfx** [comment]
Out of curiosity, if I am going to handle this case myself, is it sufficient to catch the `socket.timeout` exception, and then try and pop and close the connection from `h.connections`?

**Comment by temoto** [comment]
@justinfx sounds good. I'd start from a test looking like this:

```python
  def handler(request):
    if request.number == 1:
      time.sleep(2)
      return tests.http_response_bytes(status=500)
    return tests.http_response_bytes(status=200)

  http = httplib2.Http(timeout=0.5)
  with tests.server_request(handler, request_count=2) as uri:
    with tests.assert_raises(...):
      http.request(uri)
    response, _ = http.request(uri)
    assert response.status == 200
```

**Comment by justinfx** [comment]
@temoto I have a fix and a test locally. The fix works when I manually verify it, but I am having some trouble getting it to replicate the broken behaviour in the test because of the way it seems a new connection is being swapped in already by the test behaviour.  I will end  up submitting a wip MR for this, but thought in the meantime I would ask to see if you know off the top of your head why the test would be side stepping the standard logic of the same connection being reused on the second request?

**Comment by temoto** [comment]
@justinfx I don't see your code.

**Comment by thehesiod** [comment]
nice!  I was just about to fix this myself ;)

**Comment by ClamsTheCat** [comment]
@justinfx commits fixed my issue as well

**Comment by temoto** [comment]
Please try latest release v0.12.0 with Justin fix.

**Comment by justinfx** [comment]
@temoto I didn't see that this was merged. There is no mention of it in the changelog and this issue is still open.
Are you referring to this other thing that came from a suggestion I had made? 
211d6f07dc5fdb9339c525f746ad8944967a1ea9

**Comment by temoto** [comment]
@justinfx yes I confused things up, sorry.

**Comment by temoto** [comment]
Fix by Justin is merged in master now.

**Comment by justinfx** [comment]
Thanks!

**Comment by max-sixty** [comment]
Can this be closed now?

**Comment by temoto** [comment]
@max-sixty thanks
