### ISSUE TITLE
py2 support broken by commit bd9ee252c8f09?

### ISSUE THREAD

**Issue by alexhudson** [httplib2/httplib2#189]
Hi @temoto 

This commit changes some code on the python2 branch which doesn't appear to be valid.

There is an apparent list comprehension in the WWW-Authenticate header parser here:

https://github.com/httplib2/httplib2/blob/master/python2/httplib2/auth.py#L55

I would expect the `challenge["params"].asDict() .... for challenge in params` stanza to be enclosed square brackets? It looks like the previous code in `http_parse_auth()` just ran this as a regular loop based on regexp parsing, but now we get this in backtrace:

```
  File "/usr/lib/python2.6/site-packages/httplib2/auth.py", line 59
    for challenge in parsed
      ^
SyntaxError: invalid syntax

```

I saw on another ticket that you're looking to pull py2 support anyway, so this may not be terribly high priority, but this appears to have broken the v0.19.0 release of the library?

**Comment by temoto** [comment]
@alexhudson sorry, Python 2.6 support is definitely gone for good. It should work on Python 2.7 for a little while though.

If you want that CVE fix at 2.6, please use `httplib2.USE_WWW_AUTH_STRICT_PARSING = True`

Please reopen if it's broken on Python 2.7.
