### ISSUE TITLE
embedded cacerts.txt file does not include ISRG_X1 CA

### ISSUE THREAD

**Issue by andrewmcguinness** [httplib2/httplib2#203]
It appears that the embedded cacerts.txt file does not include the LetsEncrypt root certificate. That didn't matter because the certificate was cross-signed by another CA, but that expired yesterday (https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/)

It looks like if the certifi lib is present it will use it instead; possibly that is best practice

Successfully worked around by pointing HTTPLIB2_CA_CERTS at my system ca certs file.

**Comment by temoto** [comment]
@andrewmcguinness yes, thank you, added ISRG CA. Join testing in #204 if you please.
