### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by MikiSoft** [httplib2/httplib2#22]
```
import httplib2, socks
h = httplib2.Http(timeout=15, proxy_info=httplib2.ProxyInfo(socks.PROXY_TYPE_SOCKS5, '127.0.0.1', 8000))
h.request('http://www.google.com/')
```

However, it seems that proxy isn't used no matter what type constant (`PROXY_TYPE_HTTP`, `PROXY_TYPE_HTTP_NO_TUNNEL` and `PROXY_TYPE_SOCKS4`) and proxy I put. Has anyone experienced such issue?

**Comment by thomasding** [comment]
I've met the same problem.
I tried
```python
socks.setdefaultproxy(socks.PROXY_TYPE_HTTP, Hostname, Port)
socks.wrapmodule(httplib2)
```
and it works for me.

**Comment by MikiSoft** [comment]
Thanks @thomasding, with that code I don't need to set `proxy_info` attribute in `httplib2.Http`, right?

**Comment by impguard** [comment]
Just to check on terminology, I assume you mean "function" or "module" when you say script. In this case, I'd assume you'd have to set httplib2.socket.socket back to Python's socket module. 

Something like:

```
import socket
import httplib2

# mock out httplib2 using code above

# when done...
httplib2.socket.socket = socket.socket
```

This is really hacky. Any idea when proxying will be supported? I'm probably going to take a stab sometime at adding support if I find time. It's unimplemented in Python3.
