### ISSUE TITLE
Update of jquery.js version?

### ISSUE THREAD

**Issue by vankatamarinov** [httplib2/httplib2#222]
Hello, community,
some of our security findings inform us of an outdated version of [jquery.js ](https://github.com/httplib2/httplib2/blob/master/doc/html/_static/jquery.js)and we see that is for httplib2. I want that is not very important but I will be glad if you can update it.

Thanks!

**Comment by temoto** [comment]
Please point to public website that uses that file.

**Comment by temoto** [comment]
httplib2 documentation hosted here https://httplib2.readthedocs.io/ uses jquery 2.0.3 from sphinx.

**Comment by temoto** [comment]
Cool, so the task here is to delete legacy doc sources from repo. Thanks.
