### ISSUE TITLE
socks proxy code not delivered for Python 3

### ISSUE THREAD

**Issue by dhduvall** [httplib2/httplib2#25]
Is there a reason that the Python 2 package delivers `socks.py`, but the Python 3 package doesn't?  It looks like the upstream project is dead, and that what's in the Python 2 package has fixes that upstream doesn't, but the Python 3 side makes you make it available separately.

I'm tempted, as part of the Solaris delivery of httplib2, to copy (and modify as necessary) `socks.py` over to the python3 directory and be done with it.  Is there a good reason not to?  Would a pull request of that work be accepted?

**Comment by rjschwei** [comment]
I don't think it is quite that straight forward. SocksiPy and SocksiPy-branch are both dead, or have been declared dead. But both have bugs, thus @Anorov started https://github.com/Anorov/PySocks. One of the differences I ran across is support for PROXY_HTTP_NO_TUNNEL with a discussion here, https://github.com/mikedougherty/SocksiPy/issues/2. Then there is a version on the defunct code.google.com here https://code.google.com/archive/p/socksipy-branch/ that has this value.

While I haven't quite figured out all the pieces, it appears convoluted and simply pulling the buggy version from python2 to python3 would not appear to as a preferred choice.
