### ISSUE TITLE
Latest release 0.9.2 is a year old (released in 2015)

### ISSUE THREAD

**Issue by Flimm** [httplib2/httplib2#34]
This GitHub repo has fixes, it would be nice if these were released to Pypi:

https://pypi.python.org/pypi/httplib2

**Comment by e-kolpakov** [comment]
+1 - one of the fixes is SNI support added [back in June](https://github.com/httplib2/httplib2/commit/8aaecf4496a2da0e902977e623a2d5e65528b6de) would be nice to have it on PyPi.

Meanwhile I have to switch to install httplib2 from github.

**Comment by poswald** [comment]
Note: There appears to be an un-patched security issue in this project as well: https://github.com/httplib2/httplib2/issues/5

@jcgregorio If you're a bit busy and not able to update the project, I think it would be a good idea to put a warning up on the README about the code being deprecated/unsupported and/or asking for help or a maintainer.

It is maybe also possible you could join https://github.com/jazzband/ to get some help on the project? Not sure how that process works…

**Comment by ktosiek** [comment]
Actually, are there any active maintainers here? Is there anything blocking the release?
I'd love to see the patch from #5 applied too, as it seems to already have been battletested in Fedora.

**Comment by temoto** [comment]
No worries, PyPI release is coming soon.

**Comment by temoto** [comment]
Review and live testing of #37 (fixes #5 ) is currently the only blocker to PyPI release. Please try `pip install -U https://github.com/httplib2/httplib2/archive/issue-5.zip` and write if it works fine. This way you can help release faster.

**Comment by temoto** [comment]
New release v0.10.1 was just uploaded on PyPI. Thanks for reminder.

**Comment by Flimm** [comment]
Thank you so much!
