### ISSUE TITLE
Migrate Wiki

### ISSUE THREAD

**Issue by louy2** [httplib2/httplib2#4]
https://github.com/jcgregorio/httplib2/wiki

**Comment by jayvdb** [comment]
I've posted to https://groups.google.com/forum/#!forum/httplib2-dev , awaiting moderation, that I believe this repo should be deleted and the original repository should be transferred to the new organisation.
https://help.github.com/articles/transferring-a-repository/

**Comment by stinky2nine** [comment]
Old wiki pages are now available at https://github.com/httplib2/httplib2/wiki.
