### ISSUE TITLE
Drop support for Python 2.6 and 3.3

### ISSUE THREAD

**Issue by temoto** [httplib2/httplib2#42]
With positive resolution, we will only support Python2.7 and 3.

Please vote with github reactions 👍  or 👎  on this issue (plus smile icon in top right corner of this box)  or write your opinion in comments.

**Comment by temoto** [comment]
ping @httplib2/maintainers

**Comment by cdent** [comment]
I made a +1 above, but I think it is more important to not have two different version trees.

And since I'm making some noise here for the first time in a long time, I'd like to apologize for my absence. It has been a massively complex time in the workplace. I hope to improve on that front.

**Comment by stinky2nine** [comment]
+1 drop Python 2.6.

**Comment by sigmavirus24** [comment]
So, I tend to be bullish about dropping support for old, unsupported, versions of things. That said, do we know what projects have a dependency on httplib2? Have those projects all dropped support for 2.6 already (or at least the largest N0 of them)?

Yes those projects can all cap their version dependency, but if 2.6 support isn't costing us very much (and a unified code-base for 2.6, 2.7, 3.3, 3.4, 3.5, 3.6 is in fact *very* possible) then I don't see a reason to drop it (just for the sake of dropping it).

**Comment by temoto** [comment]
* I don't know any way to find projects using Python2.6. You smarter people, please suggest.
* Yeah, 2.5- cost much. Supporting 2.6 is more an emotional itch.
* Haven't made it obvious, but this platform support narrowing step is aimed towards unifying code base, not just for fun.

**Comment by SuburbanFilth** [comment]
You are considering dropping the support for 2.6, but the init.py file says that Python 2.3 is required and the index.html file says the same. Am I missing something ?

**Comment by temoto** [comment]
@SuburbanFilth commonly used version syntax: `3.3+` means version >= 3.3; `2.6-` means version <= 2.6.

**Comment by hugovk** [comment]
+1 and drop Python 3.2 and 3.3 at the same time.

## Reasons for dropping old ones

* https://en.wikipedia.org/wiki/CPython#Version_history

### 2.6

* https://snarky.ca/stop-using-python-2-6/
* http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html
* http://www.python3statement.org
* Current pip 9 deprecates Python 2.6 support, pip 10 won't support it (https://github.com/pypa/pip/issues/3955)
* Not much PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796

### 3.2

* pip 8 no longer supports Python 3.2 ([link](https://pip.pypa.io/en/stable/news/))
* Coverage 4 no longer supports Python 3.2 ([link](https://bitbucket.org/ned/coveragepy/issues/407/coverage-failing-on-python-325-using))
* Requests no longer supports Python 3.2
* Virtually no PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796

### 3.3

* pip 10 will deprecate Python 3.3 support, pip 11 won't support it (https://github.com/pypa/pip/issues/3796)
* Very little PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796

**Comment by hugovk** [comment]
Here's the pip installs for httplib2 from PyPI for the last month:
```
$ pypinfo --percent --pip httplib2 pyversion
python_version percent download_count
-------------- ------- --------------
2.7              82.1%      1,540,756
3.5               9.8%        184,465
3.6               4.3%         80,906
3.4               2.8%         52,263
2.6               0.9%         16,554
3.3               0.0%            467
3.7               0.0%            340
3.2               0.0%             15
None              0.0%              6
