### ISSUE TITLE
Version 0.10.2 Deleted from PyPI

### ISSUE THREAD

**Issue by crgwbr** [httplib2/httplib2#46]
This is causing our application's build to fail:

```
Collecting httplib2==0.10.2 (from -r requirements.txt (line 72))
  Could not find a version that satisfies the requirement httplib2==0.10.2 (from -r requirements.txt (line 72)) (from versions: 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.8, 0.9, 0.9.1, 0.9.2, 0.10.3)
No matching distribution found for httplib2==0.10.2 (from -r requirements.txt (line 72))
```

We can upgrade to 0.10.3, but for the most part, versions should really never be deleted or modified once pushed to a package repository. Deletion breaks things for a lot of people.

**Comment by temoto** [comment]
Yup, I agree. That 0.10.2 was broken and thus is not included in the most part. :-)
