### ISSUE TITLE
CertificateValidationUnsupported error with v0.10.2

### ISSUE THREAD

**Issue by altaurog** [httplib2/httplib2#47]
I upgraded from 0.9.2 to v0.10.2 and now I get the following error:
```
  File "/home/ubuntu/www/ubm-60.3/lib/python2.7/site-packages/httplib2/__init__.py", line 101, in _ssl_wrap_socket
    "SSL certificate validation is not supported without "
CertificateValidationUnsupported: SSL certificate validation is not supported without the ssl module installed. To avoid this error, install the ssl module, or explicity disable validation.
```
I'm using python 2.7.3, which has ssl module built-in.

**Comment by temoto** [comment]
Please, try `pip install 'httplib2==0.10.3'`

**Comment by temoto** [comment]
Most probably, duplicate of #45

**Comment by altaurog** [comment]
Yes, it works.  Thanks for the help, and sorry for not searching more thoroughly.  (I thought I had *just* installed this virtualenv, so I figured if there was a relevant bug, it'd still be open.  Impressive response time!)
