### ISSUE TITLE
Old versions of httplib2 vanished from pypi

### ISSUE THREAD

**Issue by EnTeQuAk** [httplib2/httplib2#48]
I just noticed that old versions of httplib2 vanished from pypi: https://pypi.python.org/pypi/httplib2 - which broke our and potentially many other CI builds.

It'd be nice if you could restore them to some degree.

**Comment by temoto** [comment]
#46 v0.10.2 had security issue and so it's good you can't download it.

Versions older than 0.9.2 are only removed from listing, but available for download.

Anyway, restore unspecified versions to some degree is very vague issue.

**Comment by EnTeQuAk** [comment]
Yes, it was more related to version 0.10.2 being gone from pypi, so is 0.10.1. Even though they might have security issues it is a very bad habit of deleting anything that was uploaded to pypi unless really necessary. People rely PyPi and your versions to exist for deployments, continues integration tests and much much more.

**Comment by temoto** [comment]
Yes, I agree, it's a bad habit. Good that we figured out it was not done out of habit or to annoy people, but to prevent spreading wrong code.

If you really want httplib2 version that is unable to verify SSL certificates, apply similar diff:

```diff
--- a/requirements.txt
+++ b/requirements.txt
-httplib2==0.10.2
+https://github.com/httplib2/httplib2/archive/TAG.zip
```
