### ISSUE TITLE
Python 3 trove classifier now missing from PyPI page

### ISSUE THREAD

**Issue by cclauss** [httplib2/httplib2#50]
Originally posted as: https://github.com/jcgregorio/httplib2/issues/333

The lower left of https://pypi.org/project/httplib2/0.9.2 contains the `Programming Language :: Python :: 3` trove classifier but https://pypi.org/project/httplib2 does not. This means that scripts can no longer automatically determine the Python 3 compatibility of httplib2.

**Comment by temoto** [comment]
Does anybody knows how to fix this?
We definitely have classifiers in setup.py.

**Comment by Tinkturianec** [comment]
Maybe, is mistake in PKG-INFO file?
`diff httplib2-0.9.2/PKG-INFO httplib2-0.10.3/PKG-INFO` return:
```
1c1
< Metadata-Version: 1.1
---
> Metadata-Version: 1.0
3c3
< Version: 0.9.2
---
> Version: 0.10.3
5c5
< Home-page: https://github.com/jcgregorio/httplib2
---
> Home-page: https://github.com/httplib2/httplib2
```

From PEP 314:
```
Metadata-Version is now 1.1.
Added the Classifiers field from PEP 301 .
```

**Comment by Tinkturianec** [comment]
And when I rerun `python setup.py dist` Metadata-Version is changed to 1.1. python version is 3.6.1

**Comment by temoto** [comment]
@Tinkturianec thank you very much. I think (at least logical conclusion) the problem was that I've build package with outdated setuptools.

I've uploaded patch that creates new virtualenv and `pip install -U` for release tools. It made metadata-version: 1.1, so that's nice.

@httplib2/maintainers code review request 4802a21ff374bb5ff1a278c0de7c7dff4fbe4968 I know it's kinda trivial but I've done trivial mistakes before. :-)

**Comment by ztane** [comment]
Any progress yet? Many tools display this package as Python 2 only, due to no evidence to the contrary :D

**Comment by temoto** [comment]
@ztane next release is very likely to have proper metadata (and classifiers).

**Comment by hugovk** [comment]
This can be easily checked at https://pypi.python.org/pypi/httplib2/json

Here's one tool that mistakenly reports httplib as not ready for Python 3: https://python3wos.appspot.com/

It would also be good to explicitly report supported minor versions too. For example:
```
Programming Language :: Python :: 2
Programming Language :: Python :: 2.7
Programming Language :: Python :: 3.4
Programming Language :: Python :: 3.5
Programming Language :: Python :: 3.6
```
https://pypi.python.org/pypi?%3Aaction=list_classifiers

By the way, what minor versions does httplib2 currently support? I can't find it documented anywhere.

**Comment by cclauss** [comment]
Line 25 of the json file you mention above is the problem...  The PyPI record has no trove classifiers.  This is what Python3wos looks at so it is NOT mistaken.

**Comment by hugovk** [comment]
Quite so! I phrased that badly. Python3wos is indeed doing its job correctly based on the missing classifiers.

**Comment by cclauss** [comment]
Status update?

**Comment by temoto** [comment]
@cclauss next release should be fixed, but there was no release since then. Thanks for reminder.

**Comment by cclauss** [comment]
Just this repo, Supervisor, and the Mozilla tools left on https://python3wos.appspot.com

**Comment by temoto** [comment]
With new release 0.11.0 both py2/3 classifiers show up on https://pypi.python.org/pypi/httplib2/json
