### ISSUE TITLE
Support HTTP_PROXY for python3

### ISSUE THREAD

**Issue by kimdwkimdw** [httplib2/httplib2#53]
Need support for HTTP_PROXY, HTTPS_PROXY.

Is there any plan for merge two version(python2, python3)?
https://github.com/httplib2/httplib2/blob/master/python2/httplib2/__init__.py#L904-L919
https://github.com/httplib2/httplib2/blob/master/python3/httplib2/__init__.py#L821-L822

**Comment by temoto** [comment]
Yes, we're going to merge code. I'm not promising any dates yet.

**Comment by feugen** [comment]
Hey, I need support for HTTP_Proxy and HTTPS_Proxy too. My application is a big mess without it for various reasons, was even thinking to rewrite to Python2 :-( Will we see the merge in some weeks, months, or years?

**Comment by temoto** [comment]
Proxy support: weeks.
Single code base merge: months.

**Comment by Reupiey** [comment]
Hi, I need that support too !
I managed to get it to work by adding it myself but my coworkers would prefer a clean official version...
Thanks !

**Comment by feugen** [comment]
So, guys, any news on this? Will we ever have HTTP_PROXY support for Python3?

**Comment by temoto** [comment]
@feugen hello, it's not ready yet. I've given some time to httplib2 thanks to your reminder.

**Comment by mquattrone** [comment]
Hello, any news about that? I need this feature.

**Comment by kimdwkimdw** [comment]
Use six. I changed my code to work both 2 and 3.

@mquattrone

**Comment by temoto** [comment]
@mquattrone things are moving. Today I have almost finished merging 2/3 tests.

**Comment by kimdwkimdw** [comment]
@temoto Great! It's been almost 1 year. Sorry for opening issue.
