### ISSUE TITLE
Timeout error when using proxy with httplib2

### ISSUE THREAD

**Issue by karamjaber** [httplib2/httplib2#68]
I'm trying to use httplib2 to work with proxy but for some reason socks alwayes None.

for example the following code : 
```
import httplib2
http = httplib2.Http(proxy_info = httplib2.ProxyInfo(httplib2.socks.PROXY_TYPE_HTTP_NO_TUNNEL,myproxy,myPort) )
resp, content = http.request("http://google.com", "GET")
print(Resp)
```

Any idea why ?

**Comment by temoto** [comment]
Could you try with other random values for `myproxy, myport`?

**Comment by karamjaber** [comment]
what do you mean?

**Comment by temoto** [comment]
@karamjaber do you get same error with any other proxy address?

**Comment by karamjaber** [comment]
yes, i get this error :
```
    resp, content = http.request("http://google.com", "GET")
  File "C:\Python35\lib\site-packages\httplib2\__init__.py", line 1322, in reque
st
    (response, content) = self._request(conn, authority, uri, request_uri, metho
d, body, headers, redirections, cachekey)
  File "C:\Python35\lib\site-packages\httplib2\__init__.py", line 1072, in _requ
est
    (response, content) = self._conn_request(conn, request_uri, method, body, he
aders)
  File "C:\Python35\lib\site-packages\httplib2\__init__.py", line 995, in _conn_
request
    conn.connect()
  File "C:\Python35\lib\http\client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Python35\lib\socket.py", line 711, in create_connection
    raise err
  File "C:\Python35\lib\socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected
 party did not properly respond after a period of time, or established connectio
n failed because connected host has failed to respond
```
Which indicates that there is no proxy

**Comment by temoto** [comment]
Can you share values that produce `sock is None` error?

**Comment by karamjaber** [comment]
as in the example above.... httplib2.socks.PROXY_TYPE_HTTP_NO_TUNNEL or httplib2.socks.PROXY_TYPE_HTTP

**Comment by temoto** [comment]
@karamjaber I get this error: `NameError: name 'myproxy' is not defined`
Please post a piece of code that makes error without hidden variables.

**Comment by karamjaber** [comment]
ofcourse that you will get this error if you copy-paste this.
"myproxy" will be changed with my own proxy(can't reveal the proxy that I'm using).

**Comment by temoto** [comment]
@karamjaber please post full error output.

**Comment by karamjaber** [comment]
already posted it

**Comment by temoto** [comment]
@karamjaber so there was no `sock is None` error, actually you get `TimeoutError`?

**Comment by karamjaber** [comment]
both

**Comment by temoto** [comment]
@karamjaber please show error output with `sock is None`.

**Comment by temoto** [comment]
Please try

```
import socket
socket.create_connection((myproxy, myport), 5)
print('ok')
```

**Comment by karamjaber** [comment]
I get this error:

   ```
 socket.create_connection(("myproxy",myport), 5)
  File "C:\Python35\lib\socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Python35\lib\socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
```

**Comment by temoto** [comment]
`"myproxy" -> myproxy`
put your actual variable there, not a string in quotes.

**Comment by karamjaber** [comment]
I know.... i just changed it here to not reveal the proxy that I'm using

**Comment by temoto** [comment]
@karamjaber Please run this code

```
import socket
socket.create_connection((myproxy, myport), 5)
print('ok')
```

and play your hiding game **after** it runs.

**Comment by karamjaber** [comment]
@temoto  i don't get it.... can you please elaborate ? 

This is what i executed but instead of myproxy.com i put my own proxy:
```
import socket
socket.create_connection(("http://myproxy.com", 991), 5)
print('ok')
```

this is the error i got : 

 ```
 File "Tiota.py", line 19, in <module>
    socket.create_connection(("http://myproxy.com", 991), 5)
  File "C:\Python35\lib\socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Python35\lib\socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

```

**Comment by temoto** [comment]
@karamjaber you understood correctly.

`http://myproxy.com` is not network address. Remove `http://` prefix and try again.

**Comment by karamjaber** [comment]
Then this code is working : 
```
import socket
socket.create_connection(("myproxy.com", 991), 5)
print('ok')
```
and it print ok

**Comment by temoto** [comment]
Good. And httplib2 also works with proxy now? (remove `http://` prefix from real proxy)

**Comment by karamjaber** [comment]
No it's not working.
Same error message

**Comment by temoto** [comment]
@karamjaber edit `C:\Python35\lib\http\client.py`
before line 849 add `print('DEBUG connect', self.host, self.port)`
and try again httplib2 request code
and post output.

**Comment by karamjaber** [comment]
I added this line and i got this output:
`DEBUG connect google.com 80`
It seems like that it is stuck on line 849.
 when i change the fields `(self.host,self.port)` to my real proxy and my real port it works.

I looked at the code in httplib2.__init__ and i found out that if i change the line

```
class HTTPConnectionWithTimeout(http.client.HTTPConnection):
    def __init__(self, host, port=None, timeout=None, proxy_info=None):
        http.client.HTTPConnection.__init__(self, host, port=port,
                                            timeout=timeout)

```
to 
```
class HTTPConnectionWithTimeout(http.client.HTTPConnection):
    def __init__(self, host, port=None, timeout=None, proxy_info=None):
        http.client.HTTPConnection.__init__(self, proxy_info.proxy_host, proxy_info.proxy_port,
                                            timeout=timeout)
```

It works fine.
but it won't work fine without proxy

**Comment by temoto** [comment]
So we established that httlib2 does not use proxy in your setup. I will write again when find something useful.

**Comment by karamjaber** [comment]
I tried it also on 2 other computers...same behavior

**Comment by karamjaber** [comment]
I found out that using this resolves the problem:
```
httplib2.socks.setdefaultproxy(httplib2.socks.PROXY_TYPE_HTTP, host, port)
httplib2.socks.wrapmodule(httplib2)
```

but for some reason it makes the tool that uses it to get disconnected, any idea why ?

**Comment by temoto** [comment]
What tool? Does `httplib2.request` works then?

**Comment by karamjaber** [comment]
**httplib2.Http().request**  works if I add the mentioned code lines above.
The tool I'm using is [hangups](https://github.com/tdryer)

**Comment by temoto** [comment]
@karamjaber try to open issue in hangups, maybe tdryer or someone will help to configure hangups with proxy.

**Comment by temoto** [comment]
@karamjaber please try to update httplib2, should remove need to add setdefaultproxy/wrapmodule.
