### ISSUE TITLE
Confusing response status types

### ISSUE THREAD

**Issue by bpaczkowski** [httplib2/httplib2#72]
In the response class, we can observe this inconsistent behavior:

```
type(response)            # <class 'httplib2.Response'>
type(response.status)     # <class 'int'>
type(response['status'])  # <class 'str'>
```

I just spent half an hour debugging this before I finally looked into httplib2 source [here](https://github.com/httplib2/httplib2/blob/master/python3/httplib2/__init__.py#L1382). This piece of code seems to have been there for 12 years, may I ask what is the reason behind it?

**Comment by temoto** [comment]
According to documentation, response dict values are HTTP response headers. Headers are strings.

I've seen better naming `status str, status_code int` somewhere. We can add _code, but can't remove or change old name for compatibility reasons.
