### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] on Python3 behind Proxy

### ISSUE THREAD

**Issue by Isaacsh** [httplib2/httplib2#80]
Have just install `httplib2` on my machine (Windows 10 - 64 Bit) with `pip install` method. Already on my machine Anaconda python distribution installed. Tried to run the following but got an error:

`import os` 
`os.environ['http_proxy'] = 'http://<proxy_user>:<proxy_pass>@<proxy_host>.com:<proxy_port>'`
`os.environ['https_proxy'] = 'https://<proxy_user>:<proxy_pass>@<proxy_host>.com:<proxy_port>'`

`import httplib2`
`from httplib2 import socks`

`http = httplib2.Http(proxy_info = httplib2.ProxyInfo(socks.PROXY_TYPE_HTTP, proxy_host='myproxy.com',proxy_port=80))`

`resp, content = http.request("http://google.com", "GET")`

And here's the output:

![image](https://user-images.githubusercontent.com/7535009/33617291-583255a0-d9ad-11e7-9081-4d0d5e8a0fc3.png)

Appreciate any words of wisdom anyone can share!

**Comment by temoto** [comment]
HTTP proxy and socks proxy are completely different, not compatible protocols. First, find out what kind of proxy server you use.

**Comment by Isaacsh** [comment]
@temoto How could I do that? Please advise as am not versed enough in this subject

**Comment by temoto** [comment]
@Isaacsh read description where you got proxy information from.

**Comment by temoto** [comment]
@Isaacsh please try to update httplib2, new version should work with any proxy.

**Comment by Isaacsh** [comment]
@temoto Yup, Joy in the Mundville ...
