### ISSUE TITLE
Where is new_request() defined?

### ISSUE THREAD

**Issue by cclauss** [httplib2/httplib2#82]
https://github.com/httplib2/httplib2/search?q=new_request

flake8 testing of https://github.com/httplib2/httplib2 on Python 2.7.14

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./python2/httplib2test.py:1239:20: F821 undefined name 'new_request'
            return new_request(*args, **kwargs)
                   ^
./python3/httplib2test.py:1182:20: F821 undefined name 'new_request'
            return new_request(*args, **kwargs)
                   ^
```

**Comment by temoto** [comment]
It is not defined. Don't worry, there are bigger problems with test suite.
