### ISSUE TITLE
Improve no_proxy support

### ISSUE THREAD

**Issue by cveilleux** [httplib2/httplib2#94]
Both the py2 and new py3 support for the `no_proxy` env var use a simple `endswith` check in `bypass_host`.

- https://github.com/httplib2/httplib2/blob/master/python2/httplib2/__init__.py#L843
- https://github.com/httplib2/httplib2/blob/master/python3/httplib2/__init__.py#L800

There are no standards about the behaviour of no_proxy env var, but `endswith` is probably not what you want here.

If domain starts with a dot (example: `.example.com`): 
- Use `endswith` to match any subdomain (`foo.example.com` should match)
- Remove the dot and do an exact match (`example.com` should also match)

If domain does not start with a dot (example: `example.com`): 
- It should be an exact match.

My understanding is that the current implementation of the check will match wrong cases:

```
no_proxy='bar.com'
bypass_host('foobar.com') # TRUE! 
```
Might be a good idea to add a test for it.

See this thread: curl/curl#1208

Even the curl people are struggling with understanding / documenting the correct behaviour. There does not seem to be an authoritative document about it.

**Comment by temoto** [comment]
Fix is merged in 12b26f92e308cbfa593dcf6e1d6c794e40876928 and released on PyPI in 0.11.0
